### ISSUE TITLE
Homepage: scrape post time?

### ISSUE THREAD

**Issue by onyxfish** [nprapps/graeae#67]
Is this a thing we can pull out? Does it change?

**Comment by eads** [comment]
There's nothing about this on the home page. There is on the article page. There are also "storyDate", "pubDate", and "lastModifiedDate" fields in the XML and the related "audioRunByDate"

**Comment by eads** [comment]
I should note that "lastModifiedDate" is what appears to be displayed on the page itself.

**Comment by onyxfish** [comment]
Not really a thing.
